### ISSUE TITLE
Problema al abrir un sección del drawer

### ISSUE THREAD

**Issue by ThomasBelrayDev** [Belray-Ventec/geslub-platform-react-ui#21]
### Descripción

Al abrir el una sección de Drawer en modo minimizado, no se abre el Drawer queda minimizado, no se distingue que secciones puedo seleccionar.

### Tipo
Bug

### ¿Cuándo ocurre?
Todo el tiempo

### Antes 
![image](https://user-images.githubusercontent.com/99439903/191860763-969ff245-800d-4a48-b892-8c42ce547ca2.png)

### Después de hacer click en una sección

![image](https://user-images.githubusercontent.com/99439903/191860921-69ec040b-b4da-4f40-bab8-68bd24f1a5e9.png)

**Comment by BrianGeslubDev** [comment]
Solucionado en la v1.0.2 de la librería

Solución: se implementó una nueva propiedad al componente DrawerSubItem llamada OnStateChange que debe hacer referencia a la misma propiedad que fue pasada al componente Drawer con el fin de mostrar el drawer cuando un submenú sea abierto
